Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -83,8 +83,12 @@ jobs:
       run: echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
 
     - name: Push Docker Image
-      run: docker push oumaimakhelifi/myappdevsecops:latest
-
+      run: |
+        echo "Waiting before pushing the Docker image..."
+        sleep 10  # Attendre 10 secondes
+        echo "Pushing Docker image..."
+        docker push oumaimakhelifi/dotnetproject22:latest || { echo "Push failed"; exit 1; }
+    
     - name: Deploy Locally
       run: |
         docker pull oumaimakhelifi/myappdevsecops:latest
